// This file is automatically generated from your CSS. Any edits will be overwritten.
export const infoCardContainer: string;
export const infoCardInfo: string;
export const mobile: string;
export const desktop: string;
