// This file is automatically generated from your CSS. Any edits will be overwritten.
export const gradient: string;
export const desktop: string;
export const outer: string;
export const inner: string;
export const mobile: string;
